### ISSUE TITLE
Enable Route Control Enforcement for Import direction

### ISSUE THREAD

**Issue by alexpantea** [netascode/terraform-aci-l3out#14]
In order for the **import_route_control** route-maps to be enforced, the "Route Control Enforcement" must be enabled on the import direction. 

A new variable needs to be added in the following resource:
enforceRtctrl = ["export", "import"]

https://github.com/netascode/terraform-aci-l3out/blob/572cd78996d2737b8ea1ed373b982cba6f5eb03e/main.tf#L1-L10

**Comment by danischm** [comment]
Added in v0.2.3 .

**Comment by alexpantea** [comment]
Thanks! It works.
Will the registry.terraform.io/modules/netascode/nac-aci/aci be updated soon to include the updates?

**Comment by danischm** [comment]
It is already, though you would need to source it directly from the main branch. A new version will be released as well, though this will take some time.
